openapi: 3.1.1
info:
  title: Beckn Eligibility Schema
  description: Schema definition for Eligibility in the Beckn Protocol v2.0.1
  version: 2.0.1
  contact:
    name: Beckn Labs
    url: https://beckn.io
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
components:
  schemas:
    Eligibility:
      type: object
      properties:
        eligibleQuantity:
          type: object
          properties:
            max:
              type: number
            min:
              type: number
        eligibleRegion:
          type: string
      x-jsonld:
        '@id': schema:DefinedRegion|schema:QuantitativeValue
