openapi: 3.1.1
info:
  title: Tracking
  version: 2.1.0
  description: 'Information regarding live tracking of the fufillment of a contract


    This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification
    and MUST NOT be extended. Any domain-specific extension must use the property
    of this schema which is of type Attribute.'
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    Tracking:
      description: Information regarding live tracking of the fufillment of a contract
      title: Tracking
      type: object
      properties:
        contract:
          description: Attributes of the contract for which the tracking is performed
          allOf:
          - $ref: https://schema.beckn.io/Contract/v2.0/attributes.yaml#/components/schemas/Contract
          - required:
            - id
        status:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
        url:
          description: Link/handle to off-network tracking UI or endpoint.
          type: string
          format: uri
        trackingAttributes:
          description: Information specific to the use case for which the tracking
            is performed
          $ref: https://schema.beckn.io/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      required:
      - url
      - status
