openapi: 3.1.1
info:
  title: SupportCase
  version: 2.0.0
  description: Schema definition for the SupportCase entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    SupportCase:
      type: object
      title: SupportCase
      description: 'Attributes for the SupportCase entity in the Beckn Mobility domain.

        '
      properties: {}
