openapi: 3.1.1
info:
  title: ServiceDelivery
  version: 2.0.0
  description: Schema definition for the ServiceDelivery entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    ServiceDelivery:
      type: object
      title: ServiceDelivery
      description: 'Attributes for the ServiceDelivery entity in the Beckn Mobility domain.

        '
      properties: {}
