openapi: 3.1.1
info:
  title: VehicleJourney
  version: 2.0.0
  description: Schema definition for the VehicleJourney entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    VehicleJourney:
      type: object
      title: VehicleJourney
      description: 'Attributes for the VehicleJourney entity in the Beckn Mobility
        domain.

        '
      properties: {}
