openapi: 3.1.1
info:
  title: OnConfirmAction
  version: 2.0.0
  description: 'Beckn /beckn/on_confirm callback envelope. Sent by a BPP to a BAP
    in response to a /beckn/confirm call, returning the confirmed contract with status
    set to CONFIRMED.

    '
paths: {}
components:
  schemas:
    OnConfirmAction:
      $id: https://schema.beckn.io/OnConfirmAction/v2.0
      $schema: https://json-schema.org/draft/2020-12/schema
      description: 'Beckn /beckn/on_confirm callback envelope. Sent by a BPP to a
        BAP in response to a /beckn/confirm call, returning the confirmed contract
        with status set to CONFIRMED.

        '
      title: OnConfirmAction
      type: object
      properties:
        context:
          allOf:
          - $ref: https://schema.beckn.io/Context/attributes.yaml#/components/schemas/Context
          - type: object
            properties:
              action:
                type: string
                const: beckn/on_confirm
        message:
          type: object
          additionalProperties: true
          properties:
            contract:
              $ref: https://schema.beckn.io/Contract/attributes.yaml#/components/schemas/Contract
          required:
          - contract
      required:
      - context
      - message
      x-tags:
      - common
