openapi: 3.1.1
info:
  title: BikeAllowed
  version: 2.0.0
  description: Schema definition for the BikeAllowed entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    BikeAllowed:
      type: object
      title: BikeAllowed
      description: 'Attributes for the BikeAllowed entity in the Beckn Mobility domain.

        '
      properties: {}
