openapi: 3.1.1
info:
  title: LocationInformationRequest
  version: 2.0.0
  description: Schema definition for the LocationInformationRequest entity in the
    Beckn Mobility domain.
paths: {}
components:
  schemas:
    LocationInformationRequest:
      type: object
      title: LocationInformationRequest
      description: 'Attributes for the LocationInformationRequest entity in the Beckn
        Mobility domain.

        '
      properties: {}
