openapi: 3.1.1
info:
  title: OccupancyStatus
  version: 2.0.0
  description: Schema definition for the OccupancyStatus entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    OccupancyStatus:
      type: object
      title: OccupancyStatus
      description: 'Attributes for the OccupancyStatus entity in the Beckn Mobility
        domain.

        '
      properties: {}
