openapi: 3.1.1
info:
  title: Interchange
  version: 2.0.0
  description: Schema definition for the Interchange entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    Interchange:
      type: object
      title: Interchange
      description: 'Attributes for the Interchange entity in the Beckn Mobility domain.

        '
      properties: {}
