openapi: 3.1.1
info:
  title: Food & Beverage — Offer Attributes (v2)
  version: 2.0.0
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    FoodAndBeverageOffer:
      allOf:
      - $ref: https://schema.beckn.io/RetailCoreOffer/v2.0/attributes.yaml#/components/schemas/RetailCoreOffer
      - type: object
        additionalProperties: false
        x-jsonld:
          '@context': ./context.jsonld
          '@type': fnb:FoodAndBeverageOfferAttributes
        description: 'Food & Beverage-specific extensions to RetailCoreOfferAttributes. Covers structured customization groups for dynamic configuration.

          '
        properties:
          customization:
            type: object
            additionalProperties: false
            properties:
              groups:
                type: array
                items:
                  $ref: https://schema.beckn.io/CustomizationGroup/v2.0/attributes.yaml#/components/schemas/CustomizationGroup
