openapi: 3.1.1
info:
  title: Level
  version: 2.0.0
  description: Schema definition for the Level entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    Level:
      type: object
      title: Level
      description: 'Attributes for the Level entity in the Beckn Mobility domain.

        '
      properties: {}
