openapi: 3.1.1
info:
  title: Receipt
  version: 2.0.0
  description: Schema definition for the Receipt entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    Receipt:
      type: object
      title: Receipt
      description: 'Attributes for the Receipt entity in the Beckn Mobility domain.

        '
      properties: {}
