openapi: 3.1.1
info:
  title: FareBreakup
  version: 2.0.0
  description: Schema definition for the FareBreakup entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    FareBreakup:
      type: object
      title: FareBreakup
      description: 'Attributes for the FareBreakup entity in the Beckn Mobility domain.

        '
      properties: {}
