openapi: 3.1.1
info:
  title: FareMedium
  version: 2.0.0
  description: Schema definition for the FareMedium entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    FareMedium:
      type: object
      title: FareMedium
      description: 'Attributes for the FareMedium entity in the Beckn Mobility domain.

        '
      properties: {}
