openapi: 3.1.0
info:
  title: RideOption
  version: 2.0.0
  description: Schema definition for the RideOption entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    RideOption:
      type: object
      title: RideOption
      description: 'Attributes for the RideOption entity in the Beckn Mobility domain.

        '
      properties: {}
$id: https://schema.beckn.io/RideOption/v2.0
x-tags:
- mobility
