openapi: 3.1.1
info:
  title: Line
  version: 2.0.0
  description: Schema definition for the Line entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    Line:
      type: object
      title: Line
      description: 'Attributes for the Line entity in the Beckn Mobility domain.

        '
      properties: {}
