openapi: 3.1.1
info:
  title: DropPolicy
  version: 2.0.0
  description: Schema definition for the DropPolicy entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    DropPolicy:
      type: object
      title: DropPolicy
      description: 'Attributes for the DropPolicy entity in the Beckn Mobility domain.

        '
      properties: {}
