openapi: 3.1.1
info:
  title: Beckn Invoice Schema
  description: Schema definition for Invoice in the Beckn Protocol v2.0.1
  version: 2.0.1
  contact:
    name: Beckn Labs
    url: https://beckn.io
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
components:
  schemas:
    Invoice:
      type: object
      properties:
        '@context':
          description: CPD
          type: string
          format: uri
          const: https://schema.beckn.io/
        '@type':
          description: TPD
          type: string
          enum:
          - Invoice
          x-jsonld:
            '@id': schema:Invoice
        dueDate:
          type: string
          x-jsonld:
            '@id': schema:paymentDueDate
          format: date
          nullable: true
        id:
          description: Stable invoice identifier (system id)
          type: string
          x-jsonld:
            '@id': schema:identifier
        invoiceAttributes:
          description: Attribute Pack for tax regime (e.g., GST/VAT), e-invoice refs,
            legal boilerplate, etc.
          allOf:
          - $ref: 'https://schema.beckn.io/Attributes.yaml'
        issueDate:
          type: string
          x-jsonld:
            '@id': schema:dateIssued
          format: date
        number:
          description: Human-visible invoice number
          type: string
          x-jsonld:
            '@id': schema:confirmationNumber
        payee:
          description: Seller / issuer of the invoice
          x-jsonld:
            '@id': schema:provider
          allOf:
          - $ref: 'https://schema.beckn.io/Provider.yaml'
        payer:
          description: consumer being invoiced
          x-jsonld:
            '@id': schema:customer
          allOf:
          - $ref: 'https://schema.beckn.io/Consumer.yaml'
        costBreakup:
          type: array
          items:
            $ref: 'https://schema.beckn.io/PriceSpecification.yaml'
      required:
      - '@context'
      - '@type'
      - id
      - number
      - issueDate
      - payee
      - payer
      additionalProperties: false
