openapi: 3.1.1
info:
  title: Driver
  version: 2.0.0
  description: Schema definition for the Driver entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    Driver:
      type: object
      title: Driver
      description: 'Attributes for the Driver entity in the Beckn Mobility domain.

        '
      properties: {}
