openapi: 3.1.1
info:
  title: Beckn Context Schema
  description: Schema definition for Context in the Beckn Protocol v2.1
  version: 2.1.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
  license:
    name: CC-BY-NC-SA 4.0 International
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en
components:
  schemas:
    Context:
      description: Every API call in beckn protocol has a context. It provides a high-level overview to the receiver about
        the nature of the intended transaction. Typically, it is the BAP that sets the transaction context based on the consumer's
        location and action on their UI. But sometimes, during unsolicited callbacks, the BPP also sets the transaction context
        but it is usually the same as the context of a previous full-cycle, request-callback interaction between the BAP and
        the BPP. The context object contains four types of fields. <ol><li>Demographic information about the transaction using
        fields like `domain`, `country`, and `region`.</li><li>Addressing details like the sending and receiving platform's
        ID and API URL.</li><li>Interoperability information like the protocol version that implemented by the sender and,</li><li>Transaction
        details like the method being called at the receiver's endpoint, the transaction_id that represents an end-to-end
        user session at the BAP, a message ID to pair requests with callbacks, a timestamp to capture sending times, a ttl
        to specifiy the validity of the request, and a key to encrypt information if necessary.</li></ol> This object must
        be passed in every interaction between a BAP and a BPP. In HTTP/S implementations, it is not necessary to send the
        context during the synchronous response. However, in asynchronous protocols, the context must be sent during all interactions,
      type: object
      properties:
        action:
          $ref: 'https://schema.beckn.io/Action.yaml'
        bapId:
          description: A globally unique identifier of the BAP, Typically it is the fully qualified domain name (FQDN) of
            the BAP
          type: string
        bapUri:
          description: API URL of the BAP for accepting callbacks from BPPs.
          type: string
          format: uri
        bppId:
          description: A globally unique identifier of the BAP, Typically it is the fully qualified domain name (FQDN) of
            the BAP
          type: string
        bppUri:
          description: API URL of the BPP for accepting calls from BAPs.
          type: string
          format: uri
        messageId:
          description: This is a unique value which persists during a request / callback cycle. Since beckn protocol APIs
            are asynchronous, BAPs need a common value to match an incoming callback from a BPP to an earlier call. This value
            can also be used to ignore duplicate messages coming from the BPP. It is recommended to generate a fresh message_id
            for every new interaction. When sending unsolicited callbacks, BPPs must generate a new message_id.
          type: string
          format: uuid
        networkId:
          description: A unique identifier representing a group of platforms. By default, it is the url of the network registry
            on the Beckn network
          type: string
        timestamp:
          description: Time of request generation in RFC3339 format
          type: string
          format: date-time
        transactionId:
          description: This is a unique value which persists across all API calls from `search` through `confirm`. This is
            done to indicate an active user session across multiple requests. The BPPs can use this value to push personalized
            recommendations, and dynamic offerings related to an ongoing transaction despite being unaware of the user active
            on the BAP.
          type: string
          format: uuid
        try:
          description: A flag to indicate that this request is intended to 'try' an operation. Typically set to `false` by
            default, but set to `true` when negotiating terms, updating or cancelling an active order. When set to `true`,
            the receiver must respond with the expected consequences as per the terms of service initially agreed between
            the BAP and the BPP during the `init/on_init` cycle. For example, A BAP will set this flag to `true` when requesting
            the BPP to cancel the order. Upon receiving this the BPP could respond with updated cost, cancellation fees, reasons
            for cancellation, a cancellation form, payment links, and any additional notifications or prompts informing the
            BAP about future consequences if continued (like an account ban, or reduced rating). When both participants are
            ready to continue the transaction, this flag MUST be set back to `false`.
          type: boolean
          default: false
        ttl:
          description: The duration in ISO8601 format after timestamp for which this message holds valid
          type: string
        version:
          description: Version of beckn protocol being used by the sender
          type: string
          const: 2.1.0
