openapi: 3.1.1
info:
  title: CategoryCode
  version: 2.1.0
  description: Schema definition for CategoryCode in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    CategoryCode:
      $id: https://schema.beckn.io/CategoryCode/v2.1
      $schema: https://json-schema.org/draft/2020-12/schema
      description: Schema definition for CategoryCode in the Beckn Protocol v2.0.1
      title: CategoryCode
      x-tags:
      - common
      type: object
      properties:
        '@context':
          description: JSON-LD context URI
          type: string
          format: uri
          default: https://schema.beckn.io/
        '@type':
          description: Context-specific Type of the category code
          type: string
          default: beckn:CategoryCode
        codeValue:
          description: Category code value
          type: string
          example: electronics
          x-jsonld:
            '@id': schema:codeValue
        description:
          description: Category description
          type: string
          example: Electronic devices and equipment
          x-jsonld:
            '@id': schema:description
        name:
          description: Category name
          type: string
          example: Electronics
          x-jsonld:
            '@id': schema:name
      required:
      - '@type'
      - codeValue
      additionalProperties: false
