openapi: 3.1.0
info:
  title: VehicleCategory
  version: 2.0.0
  description: Schema definition for the VehicleCategory entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    VehicleCategory:
      type: object
      title: VehicleCategory
      description: 'Attributes for the VehicleCategory entity in the Beckn Mobility domain.

        '
      properties: {}
$id: https://schema.beckn.io/VehicleCategory/v2.0
x-tags:
- mobility
