openapi: 3.1.1
info:
  title: StationStatus
  version: 2.0.0
  description: Schema definition for the StationStatus entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    StationStatus:
      type: object
      title: StationStatus
      description: 'Attributes for the StationStatus entity in the Beckn Mobility domain.

        '
      properties: {}
