openapi: 3.1.1
info:
  title: TripRequest
  version: 2.0.0
  description: Schema definition for the TripRequest entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    TripRequest:
      type: object
      title: TripRequest
      description: 'Attributes for the TripRequest entity in the Beckn Mobility domain.

        '
      properties: {}
