openapi: 3.1.1
info:
  title: EmergencyEvent
  version: 2.0.0
  description: Schema definition for the EmergencyEvent entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    EmergencyEvent:
      type: object
      title: EmergencyEvent
      description: 'Attributes for the EmergencyEvent entity in the Beckn Mobility
        domain.

        '
      properties: {}
