openapi: 3.1.0
info:
  title: EmergencyEvent
  version: 2.0.0
  description: Schema definition for the EmergencyEvent entity in the Beckn Mobility domain.
  contact:
    name: Beckn Foundation
    url: https://beckn.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    EmergencyEvent:
      type: object
      title: EmergencyEvent
      description: 'Attributes for the EmergencyEvent entity in the Beckn Mobility domain.

        '
      properties: {}
$id: https://schema.beckn.io/EmergencyEvent/v2.0
x-tags:
- mobility
