openapi: 3.1.1
info:
  title: ContactHandle
  version: 2.0.0
  description: Schema definition for the ContactHandle entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    ContactHandle:
      type: object
      title: ContactHandle
      description: 'Attributes for the ContactHandle entity in the Beckn Mobility
        domain.

        '
      properties: {}
