openapi: 3.1.1
info:
  title: TripDescriptor
  version: 2.0.0
  description: Schema definition for the TripDescriptor entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    TripDescriptor:
      type: object
      title: TripDescriptor
      description: 'Attributes for the TripDescriptor entity in the Beckn Mobility domain.

        '
      properties: {}
