openapi: 3.1.1
info:
  title: Timetable
  version: 2.0.0
  description: Schema definition for the Timetable entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    Timetable:
      type: object
      title: Timetable
      description: 'Attributes for the Timetable entity in the Beckn Mobility domain.

        '
      properties: {}
