openapi: 3.1.1
info:
  title: VehicleDescriptor
  version: 2.0.0
  description: Schema definition for the VehicleDescriptor entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    VehicleDescriptor:
      type: object
      title: VehicleDescriptor
      description: 'Attributes for the VehicleDescriptor entity in the Beckn Mobility
        domain.

        '
      properties: {}
