openapi: 3.1.1
info:
  title: FareProduct
  version: 2.0.0
  description: Schema definition for the FareProduct entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    FareProduct:
      type: object
      title: FareProduct
      description: 'Attributes for the FareProduct entity in the Beckn Mobility domain.

        '
      properties: {}
