openapi: 3.1.1
info:
  title: OnUpdateAction
  version: 2.0.0
  description: 'Beckn /beckn/on_update callback envelope. Sent by a BPP to a BAP in
    response to a /beckn/update call (or as an unsolicited update push), returning
    the updated contract state.

    '
paths: {}
components:
  schemas:
    OnUpdateAction:
      $id: https://schema.beckn.io/OnUpdateAction/v2.0
      $schema: https://json-schema.org/draft/2020-12/schema
      description: 'Beckn /beckn/on_update callback envelope. Sent by a BPP to a BAP
        in response to a /beckn/update call (or as an unsolicited update push), returning
        the updated contract state.

        '
      title: OnUpdateAction
      type: object
      properties:
        context:
          allOf:
          - $ref: https://schema.beckn.io/Context/attributes.yaml#/components/schemas/Context
          - type: object
            properties:
              action:
                type: string
                const: beckn/on_update
        message:
          type: object
          additionalProperties: true
          properties:
            contract:
              $ref: https://schema.beckn.io/Contract/attributes.yaml#/components/schemas/Contract
          required:
          - contract
      required:
      - context
      - message
      x-tags:
      - common
