openapi: 3.1.1
info:
  title: NackUnauthorized
  version: 2.0.0
  description: 'Invalid or missing authentication credentials; signature could not
    be verified.


    This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification
    and MUST NOT be extended. Any domain-specific extension must use the property
    of this schema which is of type Attribute.'
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    NackUnauthorized:
      description: Invalid or missing authentication credentials; signature could
        not be verified.
      allOf:
      - $ref: https://schema.beckn.io/Ack/v2.0/attributes.yaml#/components/schemas/Ack
      - type: object
        properties:
          status:
            type: string
            const: NACK
          error:
            $ref: https://schema.beckn.io/Error/v2.0/attributes.yaml#/components/schemas/Error
