openapi: 3.1.1
info:
  title: TrackAction
  version: 2.1.0
  description: This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification and MUST NOT be extended. Any domain-specific extension must use the property of this schema which is of type Attribute.
  license:
    name: CC-BY-NC-SA-4.0
  contact:
    name: Beckn Labs
    url: https://beckn.io
paths: {}
components:
  schemas:
    TrackAction:
      additionalProperties: false
      x-lts: true
      description: This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification and MUST NOT be extended. Any domain-specific extension must use the property of this schema which is of type Attribute.
