openapi: 3.1.1
info:
  title: Segment
  version: 2.0.0
  description: Schema definition for the Segment entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    Segment:
      type: object
      title: Segment
      description: 'Attributes for the Segment entity in the Beckn Mobility domain.

        '
      properties: {}
