openapi: 3.1.1
info:
  title: WaitingPolicy
  version: 2.0.0
  description: Schema definition for the WaitingPolicy entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    WaitingPolicy:
      type: object
      title: WaitingPolicy
      description: 'Attributes for the WaitingPolicy entity in the Beckn Mobility
        domain.

        '
      properties: {}
