openapi: 3.1.1
info:
  title: RideRequest
  version: 2.0.0
  description: Schema definition for the RideRequest entity in the Beckn Mobility
    domain.
paths: {}
components:
  schemas:
    RideRequest:
      type: object
      title: RideRequest
      description: 'Attributes for the RideRequest entity in the Beckn Mobility domain.

        '
      properties: {}
