openapi: 3.1.1
info:
  title: Alert
  version: 2.0.0
  description: Schema definition for the Alert entity in the Beckn Mobility domain.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    TransitAlert:
      type: object
      title: Alert
      description: 'Attributes for the Alert entity in the Beckn Mobility domain.

        '
      properties: {}
