openapi: 3.1.1
info:
  title: Direction
  version: 2.0.0
  description: Schema definition for the Direction entity in the Beckn Mobility domain.
paths: {}
components:
  schemas:
    Direction:
      type: object
      title: Direction
      description: 'Attributes for the Direction entity in the Beckn Mobility domain.

        '
      properties: {}
